import React from 'react';
import { 
  Dumbbell, 
  Utensils, 
  Calendar, 
  Clock, 
  Flame, 
  Info, 
  CheckCircle2, 
  ShoppingBag,
  Droplets,
  ChevronRight,
  Menu,
  X,
  Play,
  Pause,
  SkipForward,
  RotateCcw,
  Timer,
  ChefHat,
  BookOpen,
  ListChecks,
  Search,
  Milk,
  Bell,
  BellOff,
  Plus,
  Minus,
  Settings,
  GlassWater,
  Activity,
  Wind,
  Zap,
  Brain,
  Trophy,
  Shield,
  Sun,
  Moon
} from 'lucide-react';

export const Icons = {
  Workout: Dumbbell,
  Food: Utensils,
  Calendar: Calendar,
  Clock: Clock,
  Burn: Flame,
  Info: Info,
  Check: CheckCircle2,
  Bag: ShoppingBag,
  Water: Droplets,
  ArrowRight: ChevronRight,
  Menu: Menu,
  Close: X,
  Play: Play,
  Pause: Pause,
  Skip: SkipForward,
  Reset: RotateCcw,
  Timer: Timer,
  Chef: ChefHat,
  Book: BookOpen,
  List: ListChecks,
  Search: Search,
  Milk: Milk,
  Bell: Bell,
  BellOff: BellOff,
  Plus: Plus,
  Minus: Minus,
  Settings: Settings,
  Glass: GlassWater,
  Activity: Activity,
  Wind: Wind,
  Zap: Zap,
  Brain: Brain,
  Trophy: Trophy,
  Shield: Shield,
  Sun: Sun,
  Moon: Moon
};